In [ ]:
# Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# Importing the dataset

In [12]:
dataset = pd.read_csv('Iris.csv')
print(dataset.head())
X = dataset.iloc[:,1:-1].values
y = dataset.iloc[:,-1].values

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [ ]:
# Encoding the categorical data

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [15]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
# Splitting the dataset into training and test set

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 1)

In [17]:
print(X_train)

[[6.5 2.8 4.6 1.5]
 [6.7 2.5 5.8 1.8]
 [6.8 3.  5.5 2.1]
 [5.1 3.5 1.4 0.3]
 [6.  2.2 5.  1.5]
 [6.3 2.9 5.6 1.8]
 [6.6 2.9 4.6 1.3]
 [7.7 2.6 6.9 2.3]
 [5.7 3.8 1.7 0.3]
 [5.  3.6 1.4 0.2]
 [4.8 3.  1.4 0.3]
 [5.2 2.7 3.9 1.4]
 [5.1 3.4 1.5 0.2]
 [5.5 3.5 1.3 0.2]
 [7.7 3.8 6.7 2.2]
 [6.9 3.1 5.4 2.1]
 [7.3 2.9 6.3 1.8]
 [6.4 2.8 5.6 2.2]
 [6.2 2.8 4.8 1.8]
 [6.  3.4 4.5 1.6]
 [7.7 2.8 6.7 2. ]
 [5.7 3.  4.2 1.2]
 [4.8 3.4 1.6 0.2]
 [5.7 2.5 5.  2. ]
 [6.3 2.7 4.9 1.8]
 [4.8 3.  1.4 0.1]
 [4.7 3.2 1.3 0.2]
 [6.5 3.  5.8 2.2]
 [4.6 3.4 1.4 0.3]
 [6.1 3.  4.9 1.8]
 [6.5 3.2 5.1 2. ]
 [6.7 3.1 4.4 1.4]
 [5.7 2.8 4.5 1.3]
 [6.7 3.3 5.7 2.5]
 [6.  3.  4.8 1.8]
 [5.1 3.8 1.6 0.2]
 [6.  2.2 4.  1. ]
 [6.4 2.9 4.3 1.3]
 [6.5 3.  5.5 1.8]
 [5.  2.3 3.3 1. ]
 [6.3 3.3 6.  2.5]
 [5.5 2.5 4.  1.3]
 [5.4 3.7 1.5 0.2]
 [4.9 3.1 1.5 0.1]
 [5.2 4.1 1.5 0.1]
 [6.7 3.3 5.7 2.1]
 [4.4 3.  1.3 0.2]
 [6.  2.7 5.1 1.6]
 [6.4 2.7 5.3 1.9]
 [5.9 3.  5.1 1.8]
 [5.2 3.5 1.5 0.2]
 [5.1 3.3 1.7 0.5]
 [5.8 2.7 4.

In [18]:
print(y_train)

[1 2 2 0 2 2 1 2 0 0 0 1 0 0 2 2 2 2 2 1 2 1 0 2 2 0 0 2 0 2 2 1 1 2 2 0 1
 1 2 1 2 1 0 0 0 2 0 1 2 2 0 0 1 0 2 1 2 2 1 2 2 1 0 1 0 1 1 0 1 0 0 2 2 2
 0 0 1 0 2 0 2 2 0 2 0 1 0 1 1 0 0 1 0 1 1 0 1 1 1 1 2 0 0 2 1 2 1 2 2 1 2
 0]


In [19]:
print(X_test)

[[5.8 4.  1.2 0.2]
 [5.1 2.5 3.  1.1]
 [6.6 3.  4.4 1.4]
 [5.4 3.9 1.3 0.4]
 [7.9 3.8 6.4 2. ]
 [6.3 3.3 4.7 1.6]
 [6.9 3.1 5.1 2.3]
 [5.1 3.8 1.9 0.4]
 [4.7 3.2 1.6 0.2]
 [6.9 3.2 5.7 2.3]
 [5.6 2.7 4.2 1.3]
 [5.4 3.9 1.7 0.4]
 [7.1 3.  5.9 2.1]
 [6.4 3.2 4.5 1.5]
 [6.  2.9 4.5 1.5]
 [4.4 3.2 1.3 0.2]
 [5.8 2.6 4.  1.2]
 [5.6 3.  4.5 1.5]
 [5.4 3.4 1.5 0.4]
 [5.  3.2 1.2 0.2]
 [5.5 2.6 4.4 1.2]
 [5.4 3.  4.5 1.5]
 [6.7 3.  5.  1.7]
 [5.  3.5 1.3 0.3]
 [7.2 3.2 6.  1.8]
 [5.7 2.8 4.1 1.3]
 [5.5 4.2 1.4 0.2]
 [5.1 3.8 1.5 0.3]
 [6.1 2.8 4.7 1.2]
 [6.3 2.5 5.  1.9]
 [6.1 3.  4.6 1.4]
 [7.7 3.  6.1 2.3]
 [5.6 2.5 3.9 1.1]
 [6.4 2.8 5.6 2.1]
 [5.8 2.8 5.1 2.4]
 [5.3 3.7 1.5 0.2]
 [5.5 2.3 4.  1.3]
 [5.2 3.4 1.4 0.2]]


In [20]:
print(y_test)

[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 1 0 2 1 0 0 1 2 1 2 1 2 2 0 1
 0]


In [ ]:
# Feature Scaling

In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [22]:
print(X_train)

[[ 8.03473255e-01 -5.32605965e-01  4.54251771e-01  3.80020799e-01]
 [ 1.04344393e+00 -1.25712258e+00  1.13184820e+00  7.69310398e-01]
 [ 1.16342927e+00 -4.95948874e-02  9.62449091e-01  1.15860000e+00]
 [-8.76321497e-01  1.15793281e+00 -1.35267203e+00 -1.17713760e+00]
 [ 2.03546558e-01 -1.98163920e+00  6.80117246e-01  3.80020799e-01]
 [ 5.63502576e-01 -2.91100426e-01  1.01891546e+00  7.69310398e-01]
 [ 9.23458594e-01 -2.91100426e-01  4.54251771e-01  1.20494400e-01]
 [ 2.24329733e+00 -1.01561704e+00  1.75297825e+00  1.41812640e+00]
 [-1.56409460e-01  1.88244942e+00 -1.18327293e+00 -1.17713760e+00]
 [-9.96306836e-01  1.39943835e+00 -1.35267203e+00 -1.30690080e+00]
 [-1.23627752e+00 -4.95948874e-02 -1.35267203e+00 -1.17713760e+00]
 [-7.56336157e-01 -7.74111504e-01  5.89871889e-02  2.50257599e-01]
 [-8.76321497e-01  9.16427268e-01 -1.29620566e+00 -1.30690080e+00]
 [-3.96380139e-01  1.15793281e+00 -1.40913840e+00 -1.30690080e+00]
 [ 2.24329733e+00  1.88244942e+00  1.64004552e+00  1.28836320e

In [23]:
print(X_test)

[[-0.03642412  2.3654605  -1.46560477 -1.3069008 ]
 [-0.8763215  -1.25712258 -0.44921013 -0.139032  ]
 [ 0.92345859 -0.04959489  0.34131903  0.2502576 ]
 [-0.51636548  2.12395496 -1.4091384  -1.0473744 ]
 [ 2.48326801  1.88244942  1.47064641  1.0288368 ]
 [ 0.56350258  0.67492173  0.51071814  0.509784  ]
 [ 1.28341461  0.19191065  0.73658362  1.4181264 ]
 [-0.8763215   1.88244942 -1.07034019 -1.0473744 ]
 [-1.35626285  0.43341619 -1.2397393  -1.3069008 ]
 [ 1.28341461  0.43341619  1.07538183  1.4181264 ]
 [-0.2763948  -0.7741115   0.2283863   0.1204944 ]
 [-0.51636548  2.12395496 -1.18327293 -1.0473744 ]
 [ 1.52338529 -0.04959489  1.18831457  1.1586    ]
 [ 0.68348792  0.43341619  0.3977854   0.3800208 ]
 [ 0.20354656 -0.29110043  0.3977854   0.3800208 ]
 [-1.71621887  0.43341619 -1.4091384  -1.3069008 ]
 [-0.03642412 -1.01561704  0.11545356 -0.0092688 ]
 [-0.2763948  -0.04959489  0.3977854   0.3800208 ]
 [-0.51636548  0.91642727 -1.29620566 -1.0473744 ]
 [-0.99630684  0.43341619 -1.46

In [ ]:
# Training the Decision Tree Classification model on the training set

In [24]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy')
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [ ]:
# Predicting the Test set results by comparing actual y (y_test) and predicted y(y_pred)

In [25]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [1 1]
 [0 0]
 [2 2]
 [1 1]
 [2 2]
 [0 0]
 [0 0]
 [2 2]
 [1 1]
 [0 0]
 [2 2]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [2 1]
 [0 0]
 [2 2]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [2 2]
 [1 1]
 [2 2]
 [1 1]
 [2 2]
 [2 2]
 [0 0]
 [1 1]
 [0 0]]


In [ ]:
# Making the Confusion Matrix

In [26]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [ ]:
# Calculating the accuracy of the model

In [27]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9736842105263158

In [ ]:
# Defining the predict function

In [39]:
def predictFlower(sepal_length, sepal_width, petal_length, petal_width):
    prediction = classifier.predict(sc.transform([[sepal_length, sepal_width, petal_length, petal_width]]))
    
    if(prediction == 0):
        predicted_flower = 'Iris-setosa'
        
    elif(prediction == 1):
        predicted_flower = 'Iris-versicolor'
        
    elif(prediction == 2):
        predicted_flower = 'Iris-virginica'
        
    print('Predicted Flower: ',predicted_flower)

In [ ]:
# Making predictions against new data

In [40]:
sepal_length = 7.1
sepal_width = 2.5
petal_length = 5.7
petal_width = 1.6
predictFlower(sepal_length, sepal_width, petal_length, petal_width)

Predicted Flower:  Iris-virginica


In [41]:
sepal_length = 3.5
sepal_width = 1.7
petal_length = 3.2
petal_width = 1.2
predictFlower(sepal_length, sepal_width, petal_length, petal_width)

Predicted Flower:  Iris-versicolor
